### ISSUE TITLE
After update to Fedora 33, urban-terror fails with no open gl access

### ISSUE THREAD

**Issue by millerthegorilla** [predr/urban-terror-snap#1]
Until this morning, I was able to play urban-terror using the snap with confinement and a better frame rate than the native install on my Fedora 32.
I upgraded to fedora 33 and now running urban-terror results in the app complaining about the following:
Can’t load LibGL.so.1 from /etc/ld.so.conf or current dir: no dynamic gl support in current video driver.
I checked and in the snap there is no ld.so.conf in the snap/urban-terror… /etc/ directory.
I would prefer to use this app confined rather than install --classic or install the native version.
I am guessing it may be some sort of snap configuration error with regard to Fedora 33.
I have tried reinstalling snapd and also installing urban-terror from the snap-store, by the command line also, and using the latest candidate install.
Perhaps it is a Fedora issue?

**Comment by predr** [comment]
Thanks for reporting. Another snap I'm working on also has issues on F33 so it's beginning to look like a larger snapd/fedora issue.

**Comment by predr** [comment]
Tested and it looks like [this issue](https://forum.snapcraft.io/t/apps-wont-run-and-crash-on-gnome-wayland/20322/14) is fixed now.
